
Api2Url = 'http://php-yn-api2.fwpt-php/api2'
BasePath = "/app-go"
H5UsrInvoiceUrl = 'https://static.ybsjyyn.com/app/invoice.html#/'
H5UsrServiceUrl = 'https://static.ybsjyyn.com/app/about.html#/about/service'
MyAppointmentUrl = 'https://static.ybsjyyn.com/yyn/vistApt.html#/myAppointment?login=require'
YoupinHomeUrl = 'https://yyncx.ybsjyyn.com/htmlrouter/dist/pages/index/index'
YoupinOrderUrl = 'https://yyncx.ybsjyyn.com/htmlrouter/dist/pages/member/order/index'
fwpthost = 'https://mp-gw.ybsjyyn.com/integrate/api/app'
HomeUrl = "https://yyn.ybsjyyn.com/app"
WeatherH5Url = 'https://static.ybsjyyn.com/app/weather.html#/detail'
ZuulUrl = 'http://yn-fwpt-zuul.app-middleware:8080'


[hashids]
length = 12
secret = "6ab6122836cfef95f8db"

[jwt]
expireduration = 24
secret = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC3gjXjpaeEHiJuUn9JWn6uB+4TQQSzEGVH5IalznDfhLdwjFCnlzIj/P5PuR1/1tjRbAhGu4dLJgtEl9r2nJaqiholm4GQtnzzTMEQKiSC2OOLZB+FFQRoY/e/6dU27U/mUFZXrOAOmIwIP8ZuwZ3sRU/1RF8P0jo1mN8EqDGJqwIDAQAB"

[mail]
host = "smtp.163.com"
pass = ""
port = 465
to = ""
user = ""

[mongodb]
addr = "app_mdbuser:yyn18prod01app@192.168.120.2:27017/db_yn_app?authSource=admin"
dbs = [
  "db_yn_app",
]

# [mysql]
#   [mysql.base]
#     connmaxlifetime = 60
#     maxidleconn = 60
#     maxopenconn = 10
#   [mysql.read]
#     addr = "192.168.20.7:3306"
#     name = "yn_test_app"
#     user = "order_root"
#     pass = "order@root0102"
#   [mysql.write]
#     addr = "192.168.20.7:3306"
#     name = "yn_test_app"
#     user = "order_root"
#     pass = "order@root0102"

[redis]
addr = "192.168.110.17:6379"
db = "0"
maxretries = 3
minidleconns = 5
pass = "crs-bitc7tpe:app#prod%2018"
poolsize = 10

[urltoken]
expireduration = 10
secret = "i1ydX9RtHyuJTrw7frcu"

[datacenter]
appid = "yjy-app-main"
appkey = "e7f7fac925fe65dd32b02d8ef1069d09"
host = "http://api-internal.bdc.ybsjyyn.com"

[datacenterv2]
appid = 68
host = "http://cloud9-internal.bdc.ybsjyyn.com"

[accessToken]
addr = "http://php-yn-api2.fwpt-php"
appid = "c166e296c251dbbf"
appkey = "28d81c3c1de1a8bf6f06c3366166f508e167f96a"

[kafkaES]
addr = [
  "192.168.210.8:9092",
]
topic = "kibana_log"
[kafkaSQM]
addr = [
  "192.168.110.49:9092",
]
topic = "sqm"
